### PR TITLE
Handle cookie Path when Candid is not running in root path, but in a sublocation

### LINKED ISSUE #25: Regression when candid is running in a sub-location
According to a quick bisect I did, 99d8505e3e5dfbba061b7db81b84330defe55a48 is breaking Candid for anyone who's not running it at the root of their domain.

In my case, my `location` is set to `https://services.stgraber.org/identity`. Any login attempt since that commit immediately fails with `Login failed: invalid login state`.

Looking at the commit, I suspect the cookie path needs to be updated to take the location into consideration.

@mhilton

### PR DESCRIPTION
**Pull request by TeodorPt**
See issue #25, because cookies now specify a Path, and the path is absolute, they are not being sent anymore if the service is running from a subpath. In this stack, I am fixing that by taking the path part of the Location into account. 

Because we might still want the old behavior in certain deployments (e.g. ReverseProxyCookiePath setting in apache), we are parameterizing the change, defaulting to enabled.

Sanity checked on a local apache2 & candid deployment as well, issue looks fixed.

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -108,6 +108,10 @@ type Config struct {
 	// DischargeTokenTimeout is the maximum age a discharge token can
 	// get before it becomes invalid.
 	DischargeTokenTimeout DurationString `yaml:"discharge-token-timeout"`
+
+	// UseLocationForCookiePaths instructs if the Cookie Paths are to
+	// be set relative to the Location Path or not.
+	UseLocationForCookiePaths bool `yaml:"use-location-for-cookie-paths"`
```
Comment (mhilton) [inline config/config.go]: Because not every deployment uses the charm and this was a regression I think it would be better if the changed behaviour is on by default. Therefore I think you should reverse the meaning of the setting such that the path is added unless the setting is set.

File: internal/discharger/login_sublocation_test.go [hunk 2]
```diff
@@ -0,0 +1,86 @@
+// Copyright 2015 Canonical Ltd.
```
Comment (frankban) [inline internal/discharger/login_sublocation_test.go]: 2021

File: idp/idputil/idputil.go [hunk 3]
```diff
@@ -240,3 +240,19 @@ func ServiceURL(location, dest string) string {
 	lu.Path = path.Join(lu.Path, u.Path)
 	return lu.String()
 }
+
+// CookiePathRelativeToLocation returns the Login Cookie Path
+// relative to the sub-path in the location URL given.
+func CookiePathRelativeToLocation(cookiePath, location string, useLocation bool) string {
+	if useLocation == false {
```
Comment (mhilton) [inline idp/idputil/idputil.go]: we would normally spell this `if !useLocation {` (but see above)

File: internal/discharger/login.go [hunk 4]
```diff
@@ -73,8 +73,10 @@ type loginRequest struct {
 func (h *handler) Login(p httprequest.Params, req *loginRequest) error {
 	// Store the requested discharge ID in a session cookie so that
 	// when the redirect comes back to login-complete we know the
-	// login was initiated in this session.
-	state, err := h.params.codec.SetCookie(p.Response, waitCookieName, "/login-complete", waitState{
+	// login was initiated in this session. In case Candid is running in a sub-path,
```
Comment (mhilton) [inline internal/discharger/login.go]: I don't think you need to add the second sentence to this comment. It's possibly better as another comment.

**Review by mhilton — CHANGES_REQUESTED** [review]
Looks good, some minor comments but I think the config meaning should be reversed.

File: internal/discharger/login_sublocation_test.go [hunk 5]
```diff
@@ -0,0 +1,86 @@
...
+	resp := srv.Do(c, req)
+	defer resp.Body.Close()
+	c.Assert(resp.StatusCode, qt.Equals, http.StatusOK)
+
+	cookies := resp.Cookies()
+	c.Assert(len(cookies) > 0, qt.IsTrue)
+
+	for _, cookie := range cookies {
+		dir := filepath.Dir(cookie.Path)
+		c.Assert(dir != sublocationPath, qt.IsTrue)
```
Comment (frankban) [inline internal/discharger/login_sublocation_test.go]: `c.Assert(dir, qt.Not(qt.Equals), sublocationPath)`?

File: config/config.go (hunk 1 above)
Comment (TeodorPt) [reply config/config.go]: Makes sense :) Will do.

File: internal/discharger/login_sublocation_test.go [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+
+	req, err := http.NewRequest("GET", sublocationPath+"/login", nil)
+	c.Assert(err, qt.IsNil)
+	req.Header.Set("Accept", "application/json")
+	resp := srv.Do(c, req)
+	defer resp.Body.Close()
+	c.Assert(resp.StatusCode, qt.Equals, http.StatusOK)
+
+	cookies := resp.Cookies()
+	c.Assert(len(cookies) > 0, qt.IsTrue)
```
Comment (frankban) [inline internal/discharger/login_sublocation_test.go]: `c.Assert(cookies, qt.Not(qt.HasLen), 0)` ?

File: internal/discharger/login_sublocation_test.go [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+
+	for _, cookie := range cookies {
+		dir := filepath.Dir(cookie.Path)
+		c.Assert(dir != sublocationPath, qt.IsTrue)
+	}
+}
```
Comment (frankban) [inline internal/discharger/login_sublocation_test.go:73]: Cool tests, but do you really need a suite for them or would table testing be sufficient?
```go
var cookiePathTests = []struct{
	about string
	useLocation bool
}{{
	about: "location in the cookie",
	useLocation: true,
}, {
	about: "location NOT in the cookie",
}}

func TestLoginCookiePath(t *testing.T) {
	c := qt.New(t)
	for _, test := range cookiePathTests {
		c.Run(test.about, func(c *qt.C) {
			// Set up the store and the server.
			store := candidtest.NewStore()
			p := store.ServerParams()
			p.IdentityProviders = []idp.IdentityProvider{
				static.NewIdentityProvider(static.Params{
					Name:   "test",
					Domain: "test",
					Icon:   "/static/static1.bmp",
				}),
			}
			p.UseLocationForCookiePaths = test.useLocation
			srv := candidtest.NewServerWithSublocation(c, p, map[string]identity.NewAPIHandlerFunc{
				"discharger": discharger.NewAPIHandler,
			}, sublocationPath)

			// Make the request.
			req, err := http.NewRequest("GET", sublocationPath+"/login", nil)
			c.Assert(err, qt.IsNil)
			req.Header.Set("Accept", "application/json")
			resp := srv.Do(c, req)
			defer resp.Body.Close()

			// Check the response.
			c.Assert(resp.StatusCode, qt.Equals, http.StatusOK)
			cookies := resp.Cookies()
			c.Assert(cookies, qt.Not(qt.HasLen), 0)
			for _, cookie := range cookies {
				dir := filepath.Dir(cookie.Path)
				if test.useLocation {
					c.Assert(dir, qt.Equals, sublocationPath)
				} else {
					c.Assert(dir, qt.Not(qt.Equals), sublocationPath)
				}
			}
		})
	}
```
Take it or leave it, your current implementation is totally fine.

File: idp/idputil/idputil.go [hunk 8]
```diff
@@ -240,3 +240,19 @@ func ServiceURL(location, dest string) string {
...
+		return cookiePath
+	}
+
+	relativePath := ""
+	u, err := url.Parse(location)
+	if err == nil {
```
Comment (frankban) [inline idp/idputil/idputil.go]: or check `if err != nil` and `return u.Path + cookiePath`, so you can just drop the relativePath var?

**Review by frankban — APPROVED** [review]
Looks good with some optional suggestions. But a review from @mhilton is also required here.

File: internal/discharger/login_sublocation_test.go (hunk 7 above)
Comment (TeodorPt) [reply internal/discharger/login_sublocation_test.go:73]: I like your solution much better :) I did like this due to a copy-paste-edit from login_test

**Review by mhilton — APPROVED** [review]
LGTM
